### ISSUE TITLE
Automatic add of `reviewed/ok-to-test` label for core members

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#225]
Can we please implement an automatic add of the `reviewed/ok-to-test` label to pull requests that were filed/updated by members in our `core` team?

**Comment by ccwienk** [comment]
that's also a very good idea. I shall add it to our backlog discussion

**Comment by rfranzke** [comment]
Any update here? Timeline?

**Comment by rfranzke** [comment]
ping

**Comment by AndreasBurger** [comment]
As discussed with @rfranzke I'm going to work on this now

**Comment by AndreasBurger** [comment]
As of commit b49f0a88fd8f7e7067355e8ae3ae3ea3bf401f96 (released with version 1.164.0) we will add the configured 'required labels' to pull requests created by members of our organization.
