### ISSUE TITLE
Add built docker images to release notes

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#226]
The pipeline definition describes which Docker images shall be build, e.g. https://github.com/gardener/machine-controller-manager/blob/master/.ci/pipeline_definitions#L11-L19.

For each of these Docker images, can we please have the following section at the end of the release notes:

## Docker Images
machine-controller-manager: `eu.gcr.io/gardener-project/gardener/machine-controller-manager:0.3.0`

**Comment by ccwienk** [comment]
good idea. I shall add this to our backlog discussion

**Comment by rfranzke** [comment]
ping

**Comment by rfranzke** [comment]
ping2

**Comment by rfranzke** [comment]
@petersutter can you help with this?

**Comment by petersutter** [comment]
@rfranzke I understood there is a belief that the release notes handling is broken and that there is no point to add any feature to it. 
As there seems to be a concrete idea on how to improve the release notes handling in general I assume this feature will be picked up then.

**Comment by vlerenc** [comment]
/remove lifecycle/rotten

@ccwienk Can this be done?

**Comment by ccwienk** [comment]
related pull-request: https://github.com/gardener/cc-utils/issues/226

**Comment by rfranzke** [comment]
I can't believe it... 😳😲🫨

**Comment by AndreasBurger** [comment]
Todays gardener-releases seem to include the newly generated resource-release-notes and look good to me.
@rfranzke any further wishes/remarks? If not I'll close this issue

**Comment by rfranzke** [comment]
Love it. Minor ask: Maybe sort this alphabetically?

**Comment by AndreasBurger** [comment]
Will do.

**Comment by AndreasBurger** [comment]
Release note categories (of which there currently are 1, `Docker Image`) and their entries will each be sorted with our next release, keeping both the categories and the entries in a stable order across releases while also making the lookup of entries for larger lists a bit more convenient.

Closing this issue.
