### ISSUE TITLE
Proper sorting of release notes

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#229]
The release notes of a component might consist out of the release notes of several other components, e.g. [Gardener 0.17.4](https://github.com/gardener/gardener/releases/tag/0.17.4).

Currently, the release notes are sorted alphabetically by component name.
Can we please keep this behaviour but put the release notes of the own repository at the top, and only after them all the others?

**Comment by petersutter** [comment]
should be relatively easy to do

something like:
```python
.sort_by(lambda rls_note_obj: rls_note_obj.cn_source_repo.github_repo())\
.sort_by(lambda rls_note_obj: rls_note_obj.is_current_repo(), reverse=True)\
```
https://github.com/gardener/cc-utils/blob/master/github/release_notes/renderer.py#L78

and of course the unit tests need to be adapted..
