### ISSUE TITLE
Allow tags with leading 'v'

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/cc-utils#301]
I would like to tag project releases with `v<semver>` (such as kubernetes/kubernetes, docker/docker, coreos/ignition, and etc).

**Comment by ialidzhikov** [comment]
Ref https://github.com/gardener/gardener/issues/1096#issuecomment-508649092 .


Let me add also some context. 
Without the leading `v` in the tags, projects vendoring gardener/gardener and using go modules (de facto the standard) will have the following pseudo-version in their `go.mod`:

```
require (
	github.com/gardener/gardener v0.0.0-20190628060349-06358ff44e46
)
```

which in this case corresponds to tag 0.26.1 (commit hash 06358ff44e46). Note that even if gardener/gardener releases 1.12.0 for example, this will be again recorded in `go.mod` in the format `v0.0.0-<commit_time>-<commit_hash>`.


If the tag is with the leading `v`, the `go.mod` would look like

```
require (
	github.com/gardener/gardener v0.26.1
)
```

and the go tool will properly interpret the tag as a semantic version.

/priority important-longterm

**Comment by ccwienk** [comment]
done, as of `cc-utils:1.471.0`.

**Comment by ialidzhikov** [comment]
> done, as of `cc-utils:1.471.0`.

Really nice feature. Appreciate it! 🚀
