### ISSUE TITLE
Release jobs may release non-tested commits

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#365]
A long running release job may release non-tested commits if, during the job run, new commits are pushed to master. The reason for this is that, at the end of the release pipeline, a new version bump commit is pushed (which is then tagged and released). Therefore, the automation has to rebase, and during this rebase new commits will be included in the release (although they haven't been tested/deployed/considered by this release job).

**Comment by ccwienk** [comment]
fixed.

configure your release trait(s) with the new attribute `release_commit_publishing_policy`, set if to `tag_only` (https://gardener.github.io/cc-utils/traits/release.html)
