### ISSUE TITLE
Orphaned draft release notes

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#397]
When releasing a version `x` then we often see orphaned draft releases `x-dev` that are not deleted after the release. Can you please delete them automatically?

**Comment by rfranzke** [comment]
ping

**Comment by rfranzke** [comment]
ping

**Comment by AndreasBurger** [comment]
We've made some improvements on this some time ago. Is it still happening?
I've just checked the Gardener- and landscape-Repositories and I don't see any lingering draft-release-notes.

**Comment by rfranzke** [comment]
Yes, it is still happening. Just deleted some orphaned release note manually yesterday.

**Comment by petersutter** [comment]
the dashboard currently has an orphaned draft release [1.45.1-draft](https://github.com/gardener/dashboard/releases/tag/untagged-5b64bc5cf876424e72af)

**Comment by ccwienk** [comment]
I assume / hope this issue is actually already resolved (hence closing it). please do re-open in case issues still persist.
