### ISSUE TITLE
Easy way to deploy a non-released version

### ISSUE THREAD

**Issue by petersutter** [gardener/cc-utils#406]
**What would you like to be added**:
It would be nice to have an easy way (e.g. by running a job) to deploy a non-released version (e.g. master or a PR) to the dev landscape.

**Why is this needed**:
This would help to get early feedback before releasing the component.

**Comment by rfranzke** [comment]
Please keep in mind that there is not only the version that might be changed for a non-released versions. There are also `deploy` scripts etc. that might be adapted to a new version. This should be reflected/possible in the solution as well.

Btw, any plans/progress?

**Comment by ccwienk** [comment]
@petersutter , @rfranzke (/cc @schrodit ): I think this is a topic that will be covered by the landscaper, and that will thus not reasonably be integrated into the legacy deployment gear; do you concur (if so, I suggest to close this ticket)?

**Comment by ccwienk** [comment]
since @schrodit concured, I am closing this ticket
