### ISSUE TITLE
Please upgrade your Kubernetes client

### ISSUE THREAD

**Issue by vlerenc** [gardener/cc-utils#674]
**What would you like to be added**:
Please upgrade to Kubernetes client `v19.15.0` or newer.

**Why is this needed**:
Client `v11` is for Kubernetes clusters `v1.15`, which are since long no longer supported (the client versioning improved with `v17` matching the Kubernetes version, btw: https://github.com/kubernetes-client/python). So, that's one reason why this would be good.

I have to use both (@ccwienk you suggested the same), but since I have also other security reasons for `v19.15.0` or newer, I have no choice anymore and now made an ugly hack.

Please note that the problem always is that we may encounter clusters of different versions and the client should fit (but only one module of one version can be loaded unless we get more inventive). It all depends on the Kubernetes API groups. But, the closer we are, the better.

**Comment by ccwienk** [comment]
@vlerenc : done as of `1.1561.0`

**Comment by vlerenc** [comment]
Thanks @ccwienk !
